### ISSUE TITLE
Crash when JIT is enabled

### ISSUE THREAD

**Issue by midwan** [PandTomB/uae4arm#1]
Hi @PandTomB,

I found a bug in the JIT code that causes a crash, as documented on https://github.com/midwan/amiberry/issues/314

If JIT is enabled, running an MD5 hashing tool a few times eventually crashes the emulator. If you disable JIT, the crash does not occur.

**Comment by PandTomB** [comment]
Fixed: MVMEL #<data>.W,(An)+
