### ISSUE TITLE
Open Pandora update

### ISSUE THREAD

**Issue by sprudel79** [PandTomB/uae4arm#14]
Hi everyone,
as a long-term Open Pandora user (I've been using it since 2008!) and a uae4arm user I am happy to see that the uae4arm project is still active. I am wondering if there's a chance to update the Open Pandora package of uae4arm (a PND file) as well to get the latest updates.
Thanks in advance!
Sprudel

**Comment by PandTomB** [comment]
The changes in the last few years we did in uae4arm requires a faster CPU than the Pandora has and at least two cores. I think, for the Pyra, we can create a version based on the current source.
Regards,
Tom

**Comment by sprudel79** [comment]
Thanks @PandTomB, that would be great. I have pre-ordered the Pyra already but I don't expect to get it in the next few years ;-) So I have to stick with my OpenPandora or a different handheld until my Pyra arrives. 
Independent from that I totally appreciate your work and I am happy to read about your plans with uae4arm and the Pyra.
Best regards,
Sprudel
