### ISSUE TITLE
OS 3.5 and 3.9 installers fail if JIT is enabled

### ISSUE THREAD

**Issue by midwan** [PandTomB/uae4arm#2]
As documented here: https://github.com/midwan/amiberry/issues/39

This seems to be related to memory allocation when JIT is enabled, as it works if we disable JIT.
It's not only with these installers that it fails, I've seen it with a few others as well - perhaps it's related to the size of the installer scripts?

**Comment by solskogen** [comment]
Same thing happens with the BoingBags

**Comment by PandTomB** [comment]
Fixed (CMPA.W)
