### ISSUE TITLE
IPF Files

### ISSUE THREAD

**Issue by Panderner** [PandTomB/uae4arm#3]
Where to Play IPF files This means for Uncracked Amiga Games, it only recognize ADF files To play Games and lots of cracked ADFs, but I can't to play IPF Games.

**Comment by CypherXG** [comment]
Did you compile the capsimg.so file in the capsimg dir?
If not....take this file (capsimg.so) in the zip archive: 
[capsimg.zip](https://github.com/PandTomB/uae4arm/files/2710434/capsimg.zip)
and put it in the capsimg dir. Then you can play IPF files.
I hope i can help you with this.
Best regards and Merry Christmas...
P.S. If you don't have the dir try Amiberry:
https://github.com/midwan/amiberry

**Comment by Panderner** [comment]
Where is capsimg directory

**Comment by Panderner** [comment]
But I'm using Android

**Comment by PandTomB** [comment]
Enabled CAPS/IPF support using capsimg from FS-UAE.

**Comment by Panderner** [comment]
Thanks but where is CAPSimg directory it's says CAPSimg.so not found

**Comment by Panderner** [comment]
Because I'm using Android

**Comment by PandTomB** [comment]
You have to create capsimg.so for your device from source: https://github.com/FrodeSolheim/capsimg
Copy the file capsimg.so to the same folder as uae4arm.

**Comment by Panderner** [comment]
Where is uae4arm folder I'm using Android
