### ISSUE TITLE
32-bit JIT FPU crashes emulator if Modeler.FP is started

### ISSUE THREAD

**Issue by midwan** [PandTomB/uae4arm#4]
This only seems to happen with the 32-bit targets, AARCH64 is unaffected in my tests.

The issue is:
- If we try to start "Modeler.FP" (from the Lightwave package), the emulator crashes with a SIGBUS.
- The crash only occurs if "JIT FPU" is enabled.

The crash occurs in `m68k_run_jit()` of `newcpu.cpp`, and specifically in the line:
```
((compiled_handler*)pushall_call_handler)();
```

I can provide you with a ready made environment in an HDF if you'd like to test this on your side as well.

**Comment by midwan** [comment]
A bit more info on this:

The `SIGBUS` crash seems to be due to an alignment exception. Specifically, I got this:
`Unhandled fault: alignment exception (0xa21) at 0x2827ca76`

**Comment by PandTomB** [comment]
I will check this in the next days.

**Comment by midwan** [comment]
@PandTomB Great, thanks! And welcome back :)

**Comment by PandTomB** [comment]
Fixed it. Maybe this also solves the problem with workbench 3.1.4.
