### ISSUE TITLE
32-bit JIT problem: Workbench 3.1.4.x fails to load

### ISSUE THREAD

**Issue by midwan** [PandTomB/uae4arm#6]
Hi Tom,
We've found this bug in 32-bit JIT (64-bit works fine!), as documented here:
https://github.com/midwan/amiberry/issues/559

**Comment by PandTomB** [comment]
I can´t fix this, because I don`t have kickstart/workbench 3.1.4.
Sorry.

**Comment by midwan** [comment]
@PandTomB 
What if I donated a copy to you? :)
Send me your details at midwan at gmail dot com and I can take care of it.

**Comment by PandTomB** [comment]
Another hint which may solve this: use -O3 instead of -Ofast. -Ofast doesn´t correctly check for NaN results in floating point operations, but Amiga sometimes needs and checks for NaN or Inf.

**Comment by midwan** [comment]
Thanks for the suggestion.
Tried it, unfortunately it didn't make a difference. 

Actually the issue is not with JIT FPU, but just with JIT. Even if I disable JIT FPU in the settings I can still recreate this, as long as I'm running the 32-bit version.

The 64-bit version works without this problem (tested on Manjaro ARM aarch64).

**Comment by midwan** [comment]
Not sure if this helps you, but I've tested the minimal environment needed to recreate this:

- Use the 3.1.4 ROM (e.g. A1200)
- Boot with no startup sequence
- Run something that shows the problem - e.g. `ed` or `LoadWB`. Optionally assign ENV: somewhere so LoadWB won't nag you about it.
- The CPU seems to freeze, but the rest is still responsive (e.g. mouse, click events, another shell window if you had it open would still accept input - but not execute anything).

The smallest program that shows this is probably `LoadWB`, so I got the 3.1.4 one and the 3.9 one from my system, and disassembled both of them. Unfortunately I am not good at assembly, but I was hoping it might help you.

I'm attaching them below, in case this helps.

[LoadWB.zip](https://github.com/PandTomB/uae4arm/files/4129271/LoadWB.zip)

**Comment by PandTomB** [comment]
The disassembled code won't help because there are lot of library calls. As long as this problem doesn't occurs in a different configuration, I can't fix it.

**Comment by Retro1968** [comment]
Another configuration with AmigaOS 3.1.4.1? I do not exactly understand what you need.

**Comment by midwan** [comment]
@Retro1968 I believe he means that since he doesn't have OS 3.1.4 he needs this recreated in another environment.

@PandTomB like I mentioned above, I could arrange for you to get a copy of OS 3.1.4 - consider it a donation from the community. You've been very helpful with your work on this project, I think the least we could do is help you back with something.

**Comment by Retro1968** [comment]
A good idea midwan!!!

To reproduce that error you must not load a workbench hdd file. Boot instead the Floppy Disk "Install3_1_4.adf" to make it simple for you. I just tried it. Without JIT it loads, with JIT it stucks.

So all you need to reproduce is the 3.1.4 ROM and the "Install3_1_4.adf" with Amiberry 3.0.11 on Raspbian Buster.

**Comment by digitalMedic** [comment]
> @PandTomB
> What if I donated a copy to you? :)
> Send me your details at midwan at gmail dot com and I can take care of it.

I would chip in some funds to help cover the cost of this as well to get this bug fixed.  :)

**Comment by Retro1968** [comment]
A good news. Thx!  :-)

In addition i report that i use an Amiga 1200 configuration with an Amiga 1200 3.1.4 ROM, but i guess that this error happens with other Amigaconfigurations too.

**Comment by midwan** [comment]
@PandTomB 
This seems to be fixed with 5b287eed63eb2a7f93c4cea5b7cf98b58ae355f5 
I did some quick tests and it behaves normally. Thanks!
