### ISSUE TITLE
64-bit vs 32-bit JIT issue

### ISSUE THREAD

**Issue by midwan** [PandTomB/uae4arm#9]
Hi @PandTomB 
Today we run into an issue that only occurs with the 64-bit version of JIT, while it works on the 32-bit one.

The Amiberry issue is here: https://github.com/midwan/amiberry/issues/720
Steps to recreate
* Get the game ADF (https://flashtro.com/river-raid-reloaded/)
* Use a configuration with JIT enabled (e.g. A1200 with JIT)
* Start the game

The enemy sprites don't appear correctly (incorrect colors, almost invisible) on the 64-bit version. However, things work normally on the 32-bit version.

Is this something you could look into, you think?

**Comment by Retro1968** [comment]
Raspberry Pi 4, Manjaro Linux 64 Bit, Amiga OS 3.1.4.1. Running River Raid Reloaded.

Thank you Midwan for your report of the error. I would like to add that the enemy sprites are completely invisible to me, while the collision queries still work. You can still shoot the enemies or collide with them if you accidentally hit them or bump into them.

**Comment by Retro1968** [comment]
Raspberry Pi 4, Manjaro Linux 64 Bit, amiberry 3.3 64-Bit, Amiga OS 3.1.4.1.

I would like to report another JIT problem with the amiberry 64-bit version.

The game "Genetic Species" runs without errors if JIT is activated. But if you want to enter the level code in the game menu, which consists of letters,  this is not possible. The letter "A" can be entered, with many other letters there is no output at all. If you leave the game and try to enter any letters in an editor, all keyboard entries work correctly. If JIT is deactivated you can easily enter the level codes in "Genetic Species".

With activated JIT under the 32-bit version of amiberry under RetroPie there are no problems in "Genetic-Species" when entering the level codes.

With both versions of amiberry, the background music of "Genetic Species" cracks, which is played from the CD integrated as an image. Only the first melody in the first level works without cracks. The intro video also jerked in both versions.

Cheers
Retro1968

**Comment by midwan** [comment]
@PandTomB 
This is still an issue on aarch64, even after the latest commit.

For your reference, here's how it looks like (notice the corrupted gfx on the enemy sprites):
![Amiberry - Amiberry_2021-01-23_12-55-49](https://user-images.githubusercontent.com/3877365/105577530-85f8cb00-5d7a-11eb-81de-6de4a8e936bc.png)

And here's how it should look like (and it does, if you disable JIT on aarch64 or run it with JIT on 32-bit):
![Amiberry - Amiberry_2021-01-23_12-50-59](https://user-images.githubusercontent.com/3877365/105577542-a4f75d00-5d7a-11eb-81b0-d69e22492a9c.png)

**Comment by PandTomB** [comment]
Fixed with commit "Bugfix JIT AARCH64 (DIVS)"

**Comment by midwan** [comment]
Confirmed, thanks!
